// <auto-generated />
using LogicaAccesoADatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoADatos.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20250414224124_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Empleado", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.Usuario.UsuarioEmail", "Email", b1 =>
                        {
                            b1.Property<int>("EmpleadoId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("Empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObjects.Usuario.UsuarioNombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("EmpleadoId")
                                .HasColumnType("int");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("Empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObjects.Usuario.UsuarioPassword", "Password", b1 =>
                        {
                            b1.Property<int>("EmpleadoId")
                                .HasColumnType("int");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("Empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
