// <auto-generated />
using System;
using LogicaAccesoADatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoADatos.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20250519001002_modificadoDeleteBehaviorAccion2")]
    partial class modificadoDeleteBehaviorAccion2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Acciones.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Acciones");

                    b.HasDiscriminator().HasValue("Accion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.ComentarioEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EnvioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EnvioID");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("EmpleadoResponableId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoEnvio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistroEnvio")
                        .HasColumnType("datetime2");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("Tracking")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoResponableId");

                    b.HasIndex("Tracking")
                        .IsUnique();

                    b.ToTable("Envios");

                    b.HasDiscriminator().HasValue("Envio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Acciones.AccionAdministracion", b =>
                {
                    b.HasBaseType("LogicaNegocio.EntidadesDominio.Acciones.Accion");

                    b.Property<int?>("AfectadoId")
                        .HasColumnType("int");

                    b.Property<int>("RealizadorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("int");

                    b.HasIndex("AfectadoId");

                    b.HasIndex("RealizadorId");

                    b.HasDiscriminator().HasValue("AccionAdministracion");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.EnvioComun", b =>
                {
                    b.HasBaseType("LogicaNegocio.EntidadesDominio.Envíos.Envio");

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("int");

                    b.HasIndex("AgenciaId");

                    b.HasDiscriminator().HasValue("EnvioComun");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.EnvioUrgente", b =>
                {
                    b.HasBaseType("LogicaNegocio.EntidadesDominio.Envíos.Envio");

                    b.Property<int?>("CiudadId")
                        .HasColumnType("int");

                    b.Property<bool>("EnvioEficiente")
                        .HasColumnType("bit");

                    b.HasIndex("CiudadId");

                    b.HasDiscriminator().HasValue("EnvioUrgente");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Cliente", b =>
                {
                    b.HasBaseType("LogicaNegocio.EntidadesDominio.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Empleado", b =>
                {
                    b.HasBaseType("LogicaNegocio.EntidadesDominio.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Administrador", b =>
                {
                    b.HasBaseType("LogicaNegocio.EntidadesDominio.Usuarios.Empleado");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Acciones.Accion", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.FechaAccion", "Fecha", b1 =>
                        {
                            b1.Property<int>("AccionId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Fecha")
                                .HasColumnType("datetime2");

                            b1.HasKey("AccionId");

                            b1.ToTable("Acciones");

                            b1.WithOwner()
                                .HasForeignKey("AccionId");
                        });

                    b.Navigation("Fecha")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.Agencia", b =>
                {
                    b.HasOne("LogicaNegocio.EntidadesDominio.Envíos.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("LogicaNegocio.ValueObjects.DireccionPostal", "Direccion", b1 =>
                        {
                            b1.Property<int>("AgenciaId")
                                .HasColumnType("int");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CodigoPostal")
                                .HasColumnType("int");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.HasKey("AgenciaId");

                            b1.ToTable("Agencias");

                            b1.WithOwner()
                                .HasForeignKey("AgenciaId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObjects.Ubicacion", "Ubicacion", b1 =>
                        {
                            b1.Property<int>("AgenciaId")
                                .HasColumnType("int");

                            b1.Property<double>("Latitud")
                                .HasColumnType("float");

                            b1.Property<double>("Longitud")
                                .HasColumnType("float");

                            b1.HasKey("AgenciaId");

                            b1.ToTable("Agencias");

                            b1.WithOwner()
                                .HasForeignKey("AgenciaId");
                        });

                    b.Navigation("Ciudad");

                    b.Navigation("Direccion")
                        .IsRequired();

                    b.Navigation("Ubicacion")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.ComentarioEnvio", b =>
                {
                    b.HasOne("LogicaNegocio.EntidadesDominio.Usuarios.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("LogicaNegocio.EntidadesDominio.Envíos.Envio", "Envio")
                        .WithMany("Comentarios")
                        .HasForeignKey("EnvioID");

                    b.Navigation("Empleado");

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.Envio", b =>
                {
                    b.HasOne("LogicaNegocio.EntidadesDominio.Usuarios.Empleado", "EmpleadoResponable")
                        .WithMany()
                        .HasForeignKey("EmpleadoResponableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmpleadoResponable");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.Usuario.UsuarioNombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObjects.Usuario.UsuarioPassword", "Password", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Acciones.AccionAdministracion", b =>
                {
                    b.HasOne("LogicaNegocio.EntidadesDominio.Usuarios.Empleado", "Afectado")
                        .WithMany()
                        .HasForeignKey("AfectadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LogicaNegocio.EntidadesDominio.Usuarios.Administrador", "Realizador")
                        .WithMany()
                        .HasForeignKey("RealizadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Afectado");

                    b.Navigation("Realizador");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.EnvioComun", b =>
                {
                    b.HasOne("LogicaNegocio.EntidadesDominio.Envíos.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.EnvioUrgente", b =>
                {
                    b.HasOne("LogicaNegocio.EntidadesDominio.Envíos.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("LogicaNegocio.ValueObjects.DireccionPostal", "Direccion", b1 =>
                        {
                            b1.Property<int>("EnvioUrgenteId")
                                .HasColumnType("int");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CodigoPostal")
                                .HasColumnType("int");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.HasKey("EnvioUrgenteId");

                            b1.ToTable("Envios");

                            b1.WithOwner()
                                .HasForeignKey("EnvioUrgenteId");
                        });

                    b.Navigation("Ciudad");

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.EntidadesDominio.Envíos.Envio", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
